name: Build dnsmasq arm64 Docker images
on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_TAG: xuwenkeke/docker-dnsmasq:1.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: xuwenkeke/docker-dnsmasq
          ref: main
          token: ${{ secrets.GH_TOKEN }}
#      -
#        name: fix dockerfile
#        run: |
#          sed -i 's/0.2.2/v0.4.0/g' Dockerfile
#          sed -i 's/webproc_linux_amd64.gz/webproc_0.4.0_linux_arm64.gz/g' Dockerfile
#          cat Dockerfile
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm,linux/arm64
          tags: ${{ env.DOCKER_HUB_TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Test
        run: |
          docker run  --platform linux/arm64 --name dnsmasq -d -p 153:53/udp -p 5380:8080 ${{ env.DOCKER_HUB_TAG }}
          netstat -natup | grep 53
          docker logs dnsmasq
          sleep 5 && curl -v http://localhost:5380/
