name: Build Bind Docker images
on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_TAG: xuwenkeke/docker-dnsmasq:1.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jpillora/docker-dnsmasq
          ref: 1.1.0
          token: ${{ secrets.GH_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: ${{ env.DOCKER_HUB_TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: Test
        run: |
          docker run --name dnsmasq -d -p 153:53/udp -p 5380:8080 ${{ env.DOCKER_HUB_TAG }}
          netstat -natup | grep 153
          netstat -natup | grep 5300
          sleep 5 && curl -v http://localhost:5300/
